MERGE (n:Control {id:'A.2.2'}) SET n.title='AI policy';
MERGE (n:Control {id:'A.2.3'}) SET n.title='Alignment with other organizational policies';
MERGE (n:Control {id:'A.2.4'}) SET n.title='Review of the AI policy';
MERGE (n:Control {id:'A.3.2'}) SET n.title='AI roles and responsibilities';
MERGE (n:Control {id:'A.3.3'}) SET n.title='Reporting of concerns';
MERGE (n:Control {id:'A.4.2'}) SET n.title='Resource documentation';
MERGE (n:Control {id:'A.4.3'}) SET n.title='Data resources';
MERGE (n:Control {id:'A.4.4'}) SET n.title='Tooling resources';
MERGE (n:Control {id:'A.4.5'}) SET n.title='System and computing resources';
MERGE (n:Control {id:'A.4.6'}) SET n.title='Human resources';
MERGE (n:Control {id:'A.5.2'}) SET n.title='AI system impact assessment process';
MERGE (n:Control {id:'A.5.3'}) SET n.title='Documentation of AI system impact assessments';
MERGE (n:Control {id:'A.5.4'}) SET n.title='Assessing impacts on individuals or groups';
MERGE (n:Control {id:'A.5.5'}) SET n.title='Assessing societal impacts';
MERGE (n:Control {id:'A.6.1.2'}) SET n.title='Objectives for responsible development';
MERGE (n:Control {id:'A.6.1.3'}) SET n.title='Processes for responsible design and development';
MERGE (n:Control {id:'A.6.2.2'}) SET n.title='AI system requirements and specification';
MERGE (n:Control {id:'A.6.2.3'}) SET n.title='Documentation of design and development';
MERGE (n:Control {id:'A.6.2.4'}) SET n.title='AI system verification and validation';
MERGE (n:Control {id:'A.6.2.5'}) SET n.title='AI system deployment';
MERGE (n:Control {id:'A.6.2.6'}) SET n.title='AI system operation and monitoring';
MERGE (n:Control {id:'A.6.2.7'}) SET n.title='AI system technical documentation';
MERGE (n:Control {id:'A.6.2.8'}) SET n.title='AI system recording of event logs';
MERGE (n:Control {id:'A.7.2'}) SET n.title='Data for development and enhancement';
MERGE (n:Control {id:'A.7.3'}) SET n.title='Acquisition of data';
MERGE (n:Control {id:'A.7.4'}) SET n.title='Quality of data for AI systems';
MERGE (n:Control {id:'A.7.5'}) SET n.title='Data provenance';
MERGE (n:Control {id:'A.7.6'}) SET n.title='Data preparation';
MERGE (n:Control {id:'A.8.2'}) SET n.title='System documentation and information for users';
MERGE (n:Control {id:'A.8.3'}) SET n.title='External reporting';
MERGE (n:Control {id:'A.8.4'}) SET n.title='Communication of incidents';
MERGE (n:Control {id:'A.8.5'}) SET n.title='Information for interested parties';
MERGE (n:Control {id:'A.9.2'}) SET n.title='Processes for responsible use';
MERGE (n:Control {id:'A.9.3'}) SET n.title='Objectives for responsible use';
MERGE (n:Control {id:'A.9.4'}) SET n.title='Intended use of the AI system';
MERGE (n:Control {id:'A.10.2'}) SET n.title='Allocation of responsibilities';
MERGE (n:Control {id:'A.10.3'}) SET n.title='Suppliers';
MERGE (n:Control {id:'A.10.4'}) SET n.title='Customers';
MERGE (n:AISystem {id:'fraud-scoring'}) SET n.title='Card fraud scoring model';
MERGE (n:AISystem {id:'support-llm'}) SET n.title='Customer support assistant';
MERGE (n:AISystem {id:'customer-data-store'}) SET n.title='Customer data store and feature pipeline';
MERGE (n:Risk {id:'R-fraud-scoring-T-EVA'}) SET n.title='Adversarial evasion', n.score=12;
MERGE (n:Risk {id:'R-fraud-scoring-T-POI'}) SET n.title='Data poisoning', n.score=25;
MERGE (n:Risk {id:'R-fraud-scoring-T-EXT'}) SET n.title='Model extraction', n.score=6;
MERGE (n:Risk {id:'R-fraud-scoring-T-BIAS'}) SET n.title='Unfair outcomes across customer groups', n.score=12;
MERGE (n:Risk {id:'R-fraud-scoring-T-DRIFT'}) SET n.title='Silent performance drift', n.score=9;
MERGE (n:Risk {id:'R-support-llm-T-INJ'}) SET n.title='Prompt injection', n.score=20;
MERGE (n:Risk {id:'R-support-llm-T-POI'}) SET n.title='Data poisoning', n.score=12;
MERGE (n:Risk {id:'R-support-llm-T-EXT'}) SET n.title='Model extraction', n.score=12;
MERGE (n:Risk {id:'R-support-llm-T-EXF'}) SET n.title='Data exfiltration through AI tools', n.score=20;
MERGE (n:Risk {id:'R-support-llm-T-LEAK'}) SET n.title='System prompt leakage', n.score=8;
MERGE (n:Risk {id:'R-support-llm-T-DRIFT'}) SET n.title='Silent performance drift', n.score=6;
MERGE (n:Risk {id:'R-support-llm-T-SUP'}) SET n.title='AI supply-chain compromise', n.score=8;
MERGE (n:Finding {id:'F-73C60060'}) SET n.title='fraud-scoring v1 fails adversarial robustness (PGD)';
MERGE (n:Finding {id:'F-EFA2BF39'}) SET n.title='Training batch \'partner-batch\' quarantined before training';
MERGE (n:Finding {id:'F-95A0FF84'}) SET n.title='Training batch \'tampered-batch\' quarantined before training';
MERGE (n:Finding {id:'F-FBBC5500'}) SET n.title='Direct production promotion attempted outside the pipeline';
MERGE (n:Finding {id:'F-9DD95F32'}) SET n.title='CR-001 Prompt injection followed by bulk data access (session_id=S-7777)';
MERGE (n:Finding {id:'F-9D568440'}) SET n.title='CR-002 Model extraction campaign (client_id=api-key-7731)';
MATCH (a {id:'fraud-scoring'}), (b {id:'R-fraud-scoring-T-EVA'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'fraud-scoring'}), (b {id:'R-fraud-scoring-T-POI'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'fraud-scoring'}), (b {id:'R-fraud-scoring-T-EXT'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'fraud-scoring'}), (b {id:'R-fraud-scoring-T-BIAS'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'fraud-scoring'}), (b {id:'R-fraud-scoring-T-DRIFT'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-INJ'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-POI'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-EXT'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-EXF'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-LEAK'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-DRIFT'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'support-llm'}), (b {id:'R-support-llm-T-SUP'}) MERGE (a)-[:HAS_RISK]->(b);
MATCH (a {id:'R-fraud-scoring-T-EVA'}), (b {id:'A.6.2.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-EVA'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-POI'}), (b {id:'A.7.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-POI'}), (b {id:'A.7.5'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-POI'}), (b {id:'A.6.2.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-EXT'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-EXT'}), (b {id:'A.6.2.8'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-BIAS'}), (b {id:'A.5.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-BIAS'}), (b {id:'A.6.2.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-fraud-scoring-T-DRIFT'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-INJ'}), (b {id:'A.6.2.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-INJ'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-INJ'}), (b {id:'A.9.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-POI'}), (b {id:'A.7.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-POI'}), (b {id:'A.7.5'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-POI'}), (b {id:'A.6.2.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-EXT'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-EXT'}), (b {id:'A.6.2.8'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-EXF'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-EXF'}), (b {id:'A.9.2'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-EXF'}), (b {id:'A.8.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-LEAK'}), (b {id:'A.6.2.4'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-LEAK'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-DRIFT'}), (b {id:'A.6.2.6'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-SUP'}), (b {id:'A.10.3'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'R-support-llm-T-SUP'}), (b {id:'A.6.2.5'}) MERGE (a)-[:TREATED_BY]->(b);
MATCH (a {id:'F-73C60060'}), (b {id:'A.6.2.4'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-EFA2BF39'}), (b {id:'A.7.4'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-EFA2BF39'}), (b {id:'A.7.5'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-EFA2BF39'}), (b {id:'A.6.2.4'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-95A0FF84'}), (b {id:'A.7.4'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-95A0FF84'}), (b {id:'A.7.5'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-95A0FF84'}), (b {id:'A.6.2.4'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-FBBC5500'}), (b {id:'A.6.2.5'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-FBBC5500'}), (b {id:'A.3.2'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-9DD95F32'}), (b {id:'A.6.2.6'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-9DD95F32'}), (b {id:'A.8.4'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-9DD95F32'}), (b {id:'A.9.2'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-9D568440'}), (b {id:'A.6.2.6'}) MERGE (a)-[:AFFECTS]->(b);
MATCH (a {id:'F-9D568440'}), (b {id:'A.6.2.8'}) MERGE (a)-[:AFFECTS]->(b);
